const menu = [
    {
        
        "id": 1,
        "title": "24 x 200 g Carny Adult",
        "gift": "2 x 85 g Carny Pouch gratis!",
        "subtitle": "Pflanzliche Bestandteile alleine sind für eine artgerechte und natürliche Ernährung ungeeignet",
        "sale": true,
        "newProduct": true,
        "category": "65a8266a6a35abd8977b07b7",
        "brand": "Animonda",
        "price": 23.89,
        "img": "./images/Product/1.jpg",
        "desc": "da Katzen durch sie nicht alle lebenswichtigen Nährstoffe erhalten und aufnehmen können. Außerdem ist insbesondere Getreide ein häufiger Auslöser von Futtermittelunverträglichkeiten und kann oft nur schwer verdaut werden. Aus diesem Grund wird bei der Rezeptur von Animonda Carny Adult vollständig auf die Zugabe von Getreide verzichtet. Auch Soja, welches ebenfalls ein hohes allergenes Potential aufweist, ist nicht enthalten.",
        
    },
    {
        "id": 2,
        "title": "Animonda Carny Adult Duo 24 x 70 g",
        "gift": "",
        "subtitle": "Für alle, die ihre Katze abseits der Hauptmahlzeiten mit etwas Delikatem verwöhnen möchten",
        "sale": false,
        "newProduct": false,
        "category": "65a8266a6a35abd8977b07b7",
        "brand": "Animonda",
        "price": 23.49,
        "img": "./images/Product/2.jpg",
        "desc": "ist das Ergänzungsfutter Animonda Carny Adult Duo eine hervorragende Wahl. Es handelt sich um Nassfutter in zwei Schichten mit Thunfisch und/oder Huhn als Hauptzutaten. Sie haben die Wahl aus mehreren Geschmacksrichtungen in Gelee, Mousse oder mit Crumble, die dank ihrer köstlichen Rezepturen auch anspruchsvolle Gourmets auf Samtpfoten zufrieden stellen.",
    },
    {
        "id": 3,
        "title": "Carny Adult 6 x 200 g",
        "gift": "",
        "subtitle": "Katzen sind Fleischliebhaber, denn es entspricht ihrer natürlichen Ernährung.",
        "sale": false,
        "newProduct": true,
        "category": "65a8266a6a35abd8977b07b7",
        "brand": "Animonda",
        "price": 5.99,
        "img": "./images/Product/3.jpg",
        "desc": "Katzen sind Fleischliebhaber, denn es entspricht ihrer natürlichen Ernährung. Pflanzliche Bestandteile alleine sind für eine artgerechte und natürliche Ernährung ungeeignet, da Katzen durch sie nicht alle lebenswichtigen Nährstoffe erhalten und aufnehmen können. Außerdem ist insbesondere Getreide ein häufiger Auslöser von Futtermittelunverträglichkeiten und kann oft nur schwer verdaut werden. Aus diesem Grund wird bei der Rezeptur von Animonda Carny Adult vollständig auf die Zugabe von Getreide verzichtet.",
    },
    {
        "id": 4,
        "title": "Integra Protect Sensitive Dose",
        "gift": "",
        "subtitle": "Getreidefreies Diät-Nassfutter für Hunde mit Futtermittelunverträglichkeiten.",
        "sale": false,
        "newProduct": false,
        "category": "65a826826a35abd8977b07b9",
        "brand": "Animonda",
        "price": 13.79,
        "img": "./images/Product/4.jpg",
        "desc": "nur eine Quelle für tierisches & pflanzliches Protein, für Ausschlussdiäten geeignet, hohe Akzeptanz, ausgewählte Zutaten",
    },
    {
        "id": 5,
        "title": "GranCarno Adult Single Protein 6 x 800 g",
        "gift": "",
        "subtitle": "Single-Animal-Protein-Futter für ausgewachsene Hunde (1-6 Jahre)",
        "sale": false,
        "newProduct": false,
        "category": "65a826826a35abd8977b07b9",
        "brand": "Animonda",
        "price": 21.49,
        "img": "./images/Product/5.jpg",
        "desc": "nur eine Fleischsorte, 100% frische Zutaten, getreide- und glutenfrei, ohne Zucker, vollwertige Rezeptur, in Deutschland hergestellt",
    }, {
        "id": 6,
        "title": "vom Feinsten 24 x 150 g",
        "gift": "Sparpaket",
        "subtitle": "Jetzt alle Sorten im Schlemmerpaket zum Sparpreis! ",
        "sale": false,
        "newProduct": false,
        "category": "65a826826a35abd8977b07b9",
        "brand": "Animonda",
        "price": 24.99,
        "img": "./images/Product/6.jpg",
        "desc": "Animonda vom Feinsten Hundefutter in höchster Qualität, ein vollwertiges, gesundes und abwechslungsreiches Hundefutter.",
    },
    {
        "id": 7,
        "title": "250 g Rocco Chings Originals",
        "gift": "50 Stück kooa Pflegetücher gratis!",
        "subtitle": "Jetzt zugreifen! Der Lieblingssnack unzähliger Hunde und das aus gutem Grund:",
        "sale": true,
        "newProduct": false,
        "category": "65a826996a35abd8977b07bb",
        "brand": "Animonda",
        "price": 4.99,
        "img": "./images/Product/7.jpg",
        "desc": "Rocco Chings Originals werden aus frischem Fleisch zubereitet - ohne Fleischmehl, ohne Fleischnebenerzeugnisse - und schonend luftgetrocknet. Das hochwertige Filetfleisch ist fettarm und besonders leicht verdaulich. Die Fleischstreifen sind getreidefrei und enthalten nur eine Proteinquelle. Daher eignen sich die Kaustreifen auch sehr gut für übergewichtige oder allergische Hunde.",
    },
    {
        "id": 8,
        "title": "Dokas Kaustange mit Entenbrust",
        "gift": "Dog Spielzeug",
        "subtitle": "Knusprige Rinderhautstangen mit schmackhaften",
        "sale": false,
        "newProduct": false,
        "category": "65a826996a35abd8977b07bb",
        "brand": "Animonda",
        "price": 4.49,
        "img": "./images/Product/8.jpg",
        "desc": "Entenbruststreifen umwickelt, zur Stärkung der Kaumuskulatur, als Beschäftigung oder Belohnung, fettarm und leicht verdaulich, ca. 12 cm lang",
    },
    {
        "id": 9,
        "title": "8in1 Delights Kauknochen Huhn",
        "gift": "Dog Spielzeug",
        "subtitle": "Fleischiger Kausnack in Knochenform",
        "sale": false,
        "newProduct": false,
        "category": "65a826996a35abd8977b07bb",
        "brand": "Animonda",
        "price": 4.49,
        "img": "./images/Product/9.jpg",
        "desc": "leckeres Hähnchenfleisch ummantelt mit bissfester Rinderhaut, geruchsneutral, ohne künstliche Farbstoffe & Geschmacksverstärker, unterschiedliche Größen erhältlich",
    },
    {
        "id": 10,
        "title": "Vom Feinsten Katze Snack-Pudding",
        "gift": "Sparpaket",
        "subtitle": "Geschmackvoller Katzensnack zum Schlecken",
        "sale": true,
        "newProduct": false,
        "category": "65a826ad6a35abd8977b07bd",
        "brand": "Animonda",
        "price": 21.49,
        "img": "./images/Product/10.jpg",
        "desc": "hochwertige Fleischauswahl in appetitlicher Pudding-Konsistenz, mit wertvollen Mineralien, im vorportionierten Schälchen, ohne Getreide- & Soja-Zusätze",
    },
    {
        "id": 11,
        "title": "Milky Shake Huhn",
        "gift": "Sparpaket 48 x 20 g",
        "subtitle": "Cremiger Snack für Katzen",
        "sale": true,
        "newProduct": false,
        "category": "65a826ad6a35abd8977b07bd",
        "brand": "Miamor",
        "price": 21.49,
        "img": "./images/Product/11.jpg",
        "desc": "wenig Laktose für gute Verträglichkeit, ohne Zucker, mit feinen Huhn-Stückchen, mit essentiellem Taurin, als flüssiges Leckerli oder Topping, im praktischen Portionstütchen",
    },
    {
        "id": 12,
        "title": "beaphar Geflügel Paste für Katzen",
        "gift": "Sparpaket",
        "subtitle": "Schmackhafte Paste zur Futterergänzung bei Katzen",
        "sale": false,
        "newProduct": false,
        "category": "65a826ad6a35abd8977b07bd",
        "brand": "Miamor",
        "price": 10.29,
        "img": "./images/Product/12.jpg",
        "desc": "mit Geflügel & Taurin für normale Herz- & Sehfunktion, ohne Getreide & Zuckerzusatz, leicht zu füttern aus der Tube, auch als Topping verwendbar",
    }
]
export default menu;
